name: GitHub Build & Run Tests WalletBuddy API

trigger:
- staging

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: Run Unit & Integration Tests
  inputs:
    command: test
