<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WalletBuddy.Application\WalletBuddy.Application.csproj" />
    <ProjectReference Include="..\WalletBuddy.Communication\WalletBuddy.Communication.csproj" />
    <ProjectReference Include="..\WalletBuddy.Exception\WalletBuddy.Exception.csproj" />
    <ProjectReference Include="..\WalletBuddy.Infrastructure\WalletBuddy.Infrastructure.csproj" />
  </ItemGroup>

</Project>
